### ISSUE TITLE
Unit Conversion

### ISSUE THREAD

**Issue by QuickRecon** [suclearnub/scubot#1]
Allow the bot to detect common unit suffixes in imperial and metric systems and convert to the corresponding unit in the opposite system. (eg feet -> meters, meters -> feet, pounds -> kilograms, etc)

**Comment by the-emerald** [comment]
Here's a list of units that I think should be included (for starters):
- kg <-> lbs
- bar <-> psi
- m <-> ft

Can't really think of anything more that a diver could use...

**Comment by QuickRecon** [comment]
I'm also putting fathoms -> meters as it sometimes appears on navy manuals/tables

**Comment by QuickRecon** [comment]
Done with commit 8fd7239dfafd906ad53bbc237a72b21a92974c9b, I'll make a pull request
