### ISSUE TITLE
Documenting modules

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#11]
It would make modules easier to manage and fix right now and in the future if they had names, description, and how they should be added to `bot.py` to make them work properly.

**Comment by QuickRecon** [comment]
right everything follows modules.md apart from the reddit reader, and thats not finished yet

**Comment by the-emerald** [comment]
Having users hunt for where to paste in code in `bot.py` would be next to impossible with more complicated modules (like the reddit post one). I love the idea of OOP-ing everything (#13). Let's do that alongside this (or first).

**Comment by QuickRecon** [comment]
I'm already half way though the conversion, won't be too long (I think)

**Comment by the-emerald** [comment]
Does modules documentation need to be rewritten?

**Comment by QuickRecon** [comment]
I've already rewritten it
