### ISSUE TITLE
Status unable to grab loaded_modules and uptime

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#17]
Reference: f31dd66

Despite making loaded_modules and uptime global variables in `bot.py`, `status.py` still seems to be throwing errors about the two variables being undefined.

Also, if `modules.help` is imported in `status.py` and `Help.loaded_modules` is used, it is simply a list with no elements inside. Perhaps a rewrite of `loaded_modules` is needed?

**Comment by QuickRecon** [comment]
you need to have an \_\_init\_\_ function to load the loaded_modules list and append it to the list after it has been made in order to access variable lists, I might change the way the loaded modules work later.

**Comment by QuickRecon** [comment]
fixed with 4705c4f9c479baedc0cd8f5b2699e81c47ddff0f
