### ISSUE TITLE
Separating trigger_string

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#18]
I think it would be good if the bot splits up `trigger_string`s into `trigger_prefix` ("!", ".", ";", etc) and `trigger_word` ("game", "role", etc.)

That way a bot can change how it's being activated without search-and-replacing each trigger_string.

**Comment by QuickRecon** [comment]
Should it be global or per module

**Comment by QuickRecon** [comment]
Will be done as part of #22
