### ISSUE TITLE
Making modules more configurable

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#22]
Right now, in order to configure a module, people have to hunt the correct variable down and change it. Perhaps we could do better and make some sort of `modules.cfg` file in the root directory or have all configurable variables easy visible on the top of each module?

**Comment by QuickRecon** [comment]
I think lets go for configurable variables for modules and a `bot.cfg` for general configuration

**Comment by the-emerald** [comment]
I'll get working on updating the documentation first, stressing the importance of designing around user-configurable variables _and_ where to put them.

**Comment by the-emerald** [comment]
I'll start the branch to separating `trigger_char` and `trigger_string` once branch `karma` has been completed and merged into `master`.

**Comment by QuickRecon** [comment]
Closed with 6ec879806833e080b6048bf2b37e8b9d11bbd0e2
