### ISSUE TITLE
Reactions and karma

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#23]
Have the bot monitor last `x` messages for a specific reaction, and add karma to the user.

**Comment by the-emerald** [comment]
Problem with code introduced in commit dd90304. Tables are missing apparently.

**Comment by QuickRecon** [comment]
DB system fixed in 47ea3eb470bba4747f57e381bd32a2823198f587

**Comment by QuickRecon** [comment]
done with f5f6d9394d6322df4f41e06053a76c01f674ded2
