### ISSUE TITLE
Karma doesn't work on messages before bot is launched

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#27]
The bot doesn't seem to see the `on_reaction_add` event if it's onto a message that was sent before the bot was turned on.

Because of the messy nature of reactions, I haven't been able to discern whether issue #26 is a misidentification of this bug.

Needs more testing before a bugfix should be made.

**Comment by QuickRecon** [comment]
Cannot comment on issue #26 but this is a known limitation of discord.py
