### ISSUE TITLE
unitconverter breaks Discord ToS

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#3]
Right now, the unit converting feature in the branch unitconverter (commit a4d7dad) breaks Discord's ToS, specifically 2.15b:

> 2.5 End Users. Without limiting any other provision of this Agreement, you agree to the following with respect to End Users and their accounts:
...
(b) You shall not **post messages**, trigger notifications, or play audio on behalf of an End User except in response to such End User **expressly opting-in to each instance** of such behavior.

I believe what that means is the bot should not post any messages unless triggered by an explicit command, such as `!units` or `!convert` (it seems to be what every bot I've seen do anyways). A good way to fix this would be to check for a prefix with `message.content.startswith`.

**Comment by QuickRecon** [comment]
Fixed with commit 3c22923cc9f448164292cf0ce646cec9093d0da7
