### ISSUE TITLE
Bot has intermittent behaviour

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#38]
Seen across multiple instances and it just hit the /r/scuba one. 

This bug is extremely intermittent. Another instance of the bot, hosted on a physically and geographically different server experiences this bug once every 24h or less, but the /r/scuba bot was up for nearly 2d before it died.

It appears that `on_ready()` is sometimes called multiple times and functionality continues, but sometimes it will keel over and die and exit. **This indicates to me that it's the Discord servers that cut off the connection, and the bot diligently reconnects; but sometimes it can't fails and thus it quits silently without trying anymore.**

One thing to take note is that in the last 24 hours, as of this report, Discord has suffered major outages. Perhaps that might be the root cause of this, so perhaps some sort of retry counter / infinite retries should be implemented.
```
emerald@ubuntu-scubot-1:~/scubot$ python3 bot.py
scubot v1.0.0
Token found. Logging in...
Login success. Your details:
User: scubot
ID [redacted]
----------
Login success. Your details:
User: scubot
ID [redacted]
----------
Login success. Your details:
User: scubot
ID [redacted]
----------
emerald@ubuntu-scubot-1:~/scubot$
```

```
emerald@xyz:~/scubot$ python3 bot.py
scubot v1.0.0
Token found. Logging in...
Login success. Your details:
User: valleybot
ID [redacted]
----------
emerald@xyz:~/scubot$
```

**Comment by QuickRecon** [comment]
I don't think this can be fixed in a safe way, if it's crashing it's probably for a good reason

**Comment by the-emerald** [comment]
I think I found the root cause of it. Unfortunately I missed the log for the last time it happened. I've enabled logging so that the next time this happens I can catch everything.

**Comment by the-emerald** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bot randomly disconnects](https://trello.com/c/opTMuTmZ/11-bot-randomly-disconnects)

**Comment by suclearnub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bot randomly disconnects](https://trello.com/c/opTMuTmZ/11-bot-randomly-disconnects)
