### ISSUE TITLE
AI @responses / canned @responses

### ISSUE THREAD

**Issue by sinetwo** [suclearnub/scubot#39]
It would be great to have canned or AI related responses from Scubot, if someone mentions it explicitly.

e.g.: sinetwo: @Scubot, you're the best!
Scutbot: @sinetwo, IKR!

**Comment by QuickRecon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Canned responses](https://trello.com/c/y87gRdUV/1-canned-responses)

**Comment by the-emerald** [comment]
Done with [mention-responses](https://github.com/scubot/mention-responses)
