### ISSUE TITLE
Assignment of roles

### ISSUE THREAD

**Issue by QuickRecon** [suclearnub/scubot#4]
Automatically assign roles of country and certification.

**Comment by the-emerald** [comment]
Added with commit b8a80c8. I won't make a PR yet as there's still role removal to do.

TODO: Implement role removal

**Comment by the-emerald** [comment]
Added in commit 2f2ae33. Will submit PR after testing for bugs.

**Comment by the-emerald** [comment]
Merged in 5e4b440. Thanks @QuickRecon!
