### ISSUE TITLE
WebHook to subreddit

### ISSUE THREAD

**Issue by QuickRecon** [suclearnub/scubot#6]

**Comment by QuickRecon** [comment]
Does having it message reddit posts automatically violate tos?

**Comment by the-emerald** [comment]
If it's isolated in its own channel (e.g. `#subreddit` or `#feed`) it should be ok, since people who don't like it can just mute the entire channel.

**Comment by QuickRecon** [comment]
Fixed with commit 8a35065065d15f0a2338a67678d610b9c5a44b72
