### ISSUE TITLE
Refactoring functions

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#7]
It might be better for organisation in the long run if we put each command/function into individual files, e.g. `modules/unit.py`, `modules/roles.py` etc. I think it's easier to manage than a giant `bot.py` file. Individual modules can be added/removed by just choosing what to import.

**Comment by QuickRecon** [comment]
I'll see what I can do

**Comment by QuickRecon** [comment]
Fixed mostly in 99545a2bd208e58f0d254fb119fd8528081df0f8, still need to add to on_message() though
